appPort: 38081
bootstrapServers: broker:29092
chuckClientId: chuck-java-consumer
chuckGroupId: chuck-java-cg
chuckTopic: chuck-java-topic
chuckAvroClientId: chuck-java-avro-consumer
chuckAvroTopic: chuck-java-avro-topic
reconnectBackoffMs: 1000
reconnectBackoffMaxMs: 300000
retryBackOffMs: 3000
schemaRegistryUrl: http://schema-registry:8081