spring:
  jmx:
    enabled: true
kafka:
  server-properties:
    bootstrap.servers: localhost:9092
    client.dns.lookup: resolve_canonical_bootstrap_servers_only
    acks: all
    schema.registry.url: http://localhost:8081
    security.protocol: PLAINTEXT
  app-properties:
    chuck-client-id: chuck-producer
    chuck-topic: chuck-spring-topic
    chuck-avro-client-id: chuck-avro-producer
    chuck-avro-topic: chuck-spring-avro-topic